### ISSUE TITLE
Find exchange volume for specific time period - Decrypt internal coinmarketcap API mechanism

### ISSUE THREAD

**Issue by reteps** [mondeja/pymarketcap#23]
Coinmarketcap keeps a record of exchange volume per coin, but is there a way to get information about a time period other than 24hr's long?

![image](https://user-images.githubusercontent.com/13869303/36760427-c5bf8b74-1be8-11e8-90ff-b0fef6f88e8a.png)

I can't seem to figure out where this exchange data is coming from since an api is not called.

my ideas are:
+ find the api that's creating the page
+ keep a script that records the volume per coin every 1/2 hour or so to compare the difference

can you help, or is this impossible

**Comment by mondeja** [comment]
The trick, I think, would be decrypt this code https://s2.coinmarketcap.com/static/cloud/compressed/currencies_main.92f13b6f.min.js (maybe you can't see the page, in that case, search it in console with debug mode of your browser) and make calls to their API with a cookie session. The problem is, as you can imagine, that the code is very crazy, even unminified. I've tried it several times, but for now nothing... Any help is welcome.

**Comment by reteps** [comment]
I think `a` is some sort of data table, if only there was some way to grab that variable + information.

**Comment by mondeja** [comment]
This is not possible, so I closed it.
