### ISSUE TITLE
Download marketcap historical-data

### ISSUE THREAD

**Issue by dgnsrekt** [mondeja/pymarketcap#44]
https://graphs2.coinmarketcap.com/global/marketcap-total/
https://graphs2.coinmarketcap.com/global/marketcap-altcoin/
https://graphs2.coinmarketcap.com/global/dominance/

**Comment by mondeja** [comment]
There are two methods that retrieve data from these endpoints:
- [`cmc.graphs.global_cap`](https://github.com/mondeja/pymarketcap/blob/master/pymarketcap/core.pyx#L703): retrieve data from `marketcap-total` and `marketcap-altcoin` endpoints. If you pass `bitcoin=True`, you will be using the first and the second otherwise.
- [`cmc.graphs.dominance`](https://github.com/mondeja/pymarketcap/blob/master/pymarketcap/core.pyx#L730): Retrieves data using third endpoint.

**Comment by dgnsrekt** [comment]
Thanks alot.
